- name: Restart networking
  systemd:
    name: "{{item}}"
    state: restarted
  with_items:
    - systemd-resolved
    - networking
    - network-manager
  become: true

- name: restart systemd-resolved
  systemd:
    name: systemd-resolved
    state: restarted
  become: true
