
- name: "Add Multimedia APT Repositories"
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - ppa:audio-recorder/ppa
    - ppa:cteehayder/ffmulticonverter
    #- ppa:sil/pick
  become: true

- name: Install Multimedia applications from APT
  apt: name={{item}} state=present
  with_items:
    - audacity
    - youtube-dl
    - shutter 
    - kazam 
    - pinta 
    - easytag
    - handbrake
    - ffmpeg
    - audio-recorder
    - brasero
    - ffmulticonverter
    - trimage
    #- pick
  become: true

- import_tasks: spotify.yml
  tags:
    - flatpack

- import_tasks: vlc.yml
  tags:
    - flatpack

- import_tasks: kdenlive.yml
  tags:
    - flatpack

- import_tasks: peek.yml
  tags:
    - flatpack

- import_tasks: lolypop.yml
  tags:
    - flatpack

- import_tasks: photos.yml
  tags:
    - flatpack

- import_tasks: bookworm.yml
  tags:
    - flatpack

- import_tasks: gravit.yml
  tags: [gravit,snap]

- import_tasks: gradio.yml
  tags:
   - gradio
   - flatpack

- import_tasks: pencil.yml
  tags: deb

- import_tasks: plex.yml
  tags: plex

- import_tasks: xnview.yml
  tags: xnview



