- name: Install Plex Media server
  apt:
    deb: https://downloads.plex.tv/plex-media-server/1.10.1.4602-f54242b6b/plexmediaserver_1.10.1.4602-f54242b6b_amd64.deb
  become: true

- name: Plex | Configure firewall to allow TCP traffic
  ufw:
    rule: allow
    proto: tcp
    src: '{{ item }}'
  with_items:
    - 32400

- name: Plex | Configure firewall to allow UDP traffic
  ufw:
    rule: allow
    proto: udp
    src: '{{ item }}'
  with_items:
    - 1900
    - 32469
    - 5353