- name: Install gnome packages
  apt: name={{item}} state=present
  with_items:
    - gnome-tweak-tool
    - gnome-shell-extensions
    - gnome-shell-extension-appindicator
    - chrome-gnome-shell
    - dconf-tools
  become: true

- name: Install gnome extensions installer
  get_url:
    url: https://github.com/brunelli/gnome-shell-extension-installer/raw/master/gnome-shell-extension-installer
    dest: /usr/local/bin/gnome-shell-extension-installer
    mode: a+x
    owner: "{{user}}"
    group: "{{group}}"
  become: true
 
- name: Install gnome Extensions
  shell: gnome-shell-extension-installer 19 55 1176 1031 1011 800 750 97 708 779 948 906 1162 820 1238 1319 120

- name: Configure Dash To dock extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/dash-to-dock/autohide',  value: "true"  }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/dock-fixed', value: "false" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/dock-position', value: "'BOTTOM'" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/multi-monitor', value: "true" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size', value: "48" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/custom-theme-running-docks', value: "true" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/background-opacity', value: "0.0" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/hotkeys', value: "false" }
    - { key: '/org/gnome/shell/extensions/dash-to-dock/click-action', value: "'minimize'" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/extend-height', value: "false" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-1', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-2', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-3', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-4', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-5', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-6', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-7', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-8', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-9', value: "[]" } 
    - { key: '/org/gnome/shell/extensions/dash-to-dock/app-hotkey-10', value: "[]" } 

- name: Configure Top Icons extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/top-icons/tray-pos', value: "'right'" }
    - { key: '/org/gnome/shell/extensions/top-icons/tray-order', value: "15" }

- name: Configure Clipboard extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/clipboard-indicator/notify-on-copy', value: "false" }
    - { key: '/org/gnome/shell/extensions/clipboard-indicator/enable-keybindings', value: "false"}

- name: Configure Open Weather extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/openweather/city', value: "'41.1494512,-8.6107884>Porto, PRT, Porto, 303201rea Metropolitana do Porto, Norte, 4000-424, Portugal >-1'" }
    - { key: '/org/gnome/shell/extensions/openweather/show-text-in-panel', value: "true" }
    - { key: '/org/gnome/shell/extensions/openweather/unit', value: "'celsius'" }
    - { key: '/org/gnome/shell/extensions/openweather/wind-speed-unit', value: "'kph'" }
    - { key: '/org/gnome/shell/extensions/openweather/position-in-panel', value: "'center'" }
    - { key: '/org/gnome/shell/extensions/openweather/geolocation-provider', value: "'openstreetmaps'" }
    - { key: '/org/gnome/shell/extensions/openweather/days-forecast', value: "3" }

- name: Configure Workspaces to dock extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/background-opacity', value: "0.2" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/customize-height', value: "true" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/customize-height-option', value: "1" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/dock-position', value: "'RIGHT'" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/dock-fixed', value: "false" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/opaque-background', value: "true" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/hide-dash ', value: "true" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/intelihide', value: "false" }
    - { key: '/org/gnome/shell/extensions/workspaces-to-dock/top-margin', value: "0" }

- name: Configure Panel OSD Extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/panel-osd/force-expand', value: "true" }
    - { key: '/org/gnome/shell/extensions/panel-osd/x-pos' , value: "100" }

- name: Configure RSS Feed Extension
  dconf:
    key: "{{item.key}}"
    value: "{{item.value}}"
    state: present
  with_items:
    - { key: '/org/gnome/shell/extensions/rss-feed/rss-feeds-list', value: "['http://scotch.io/feed', 'https://www.sitepoint.com/feed/', 'http://feeds.feedburner.com/d0od']" }
