
- name: "Add Acessories PPAs"
  apt_repository:
    repo: "{{item}}"
    state: present
  with_items:
    - ppa:webupd8team/y-ppa-manager
    - ppa:nextcloud-devs/client
  become: true

- name: Install accessories applications
  apt: name={{item}} state=present
  with_items:
    - menulibre
    - ufw
    - bleachbit
    - grsync 
    - gparted 
    - y-ppa-manager 
    - gprename
    - nextcloud-client 
    - usb-creator-gtk
  become: true

- import_tasks: 'tilix.yml'
  tags: tilix

- import_tasks: 'stacer.yml'
  tags: 
    - stacer
    - deb

- import_tasks: 'tlp.yml'
  tags: tlp

#- import_tasks: 'android-tools.yml'
#  tags: android-tools

- import_tasks: 'cryptomator.yml'
  tags: cryptomator

- import_tasks: 'ulauncher.yml'
  tags: ulauncher