- name: Stacer | Get latest version from GitHub
  shell: get_latest_gh_release.sh "oguzhaninan/Stacer"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Install stacer
  apt: deb="https://github.com/oguzhaninan/Stacer/releases/download/{{rc_version.stdout}}/stacer_{{rc_version.stdout[1:]}}_amd64.deb"
  become: true
