- name: "Add ulauncher PPA"
  apt_repository:
    repo: "ppa:agornostal/ulauncher"
    state: present
  become: true

- name: Install ulauncher
  apt: name={{item}} state=present
  with_items:
    - ulauncher
  become: true