- name: Install network tools
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - net-tools
    - nmap
    - whois
    - traceroute
    - wireshark
    - ufw
    - gufw
  become: true

- import_tasks: firewall.yml
  tags: [ 'firewall' ]

- import_tasks: dns.yml
  tags: dns