- name: Google Chrome | add google repo key
  apt_key:
    url: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  become: yes

- name: Google Chrome | add google.list
  copy: 
    content: "deb http://dl.google.com/linux/chrome/deb/ stable main"
    dest: /etc/apt/sources.list.d/google-chrome.list
    force: no
  become: yes

- name: Google Chrome | install chrome stable
  apt:
    name: google-chrome-stable
    update_cache: yes
  become: yes