
- name: Install internet applications
  apt: name={{item}} state=present
  with_items:
    - firefox
    - transmission
    - hexchat
    - uget
    - corebird
  become: true

- import_tasks: 'dropbox.yml'
  tags: dropbox

- import_tasks: 'chrome.yml'
  tags: 
    - chrome
    - browser

- import_tasks: 'discord.yml'
  tags: 
    - discord
    - communication
    - deb

- import_tasks: 'mailspring.yml'
  tags: mailspring

- import_tasks: 'franz.yml'

- import_tasks: 'ramme.yml'
  tags: 
    - ramme
    - social
    - deb

- import_tasks: 'skype.yml'
  tags: 
    - skype
    - communication
    - deb

- import_tasks: 'slack.yml'
  tags: 
   - slack
   - communication
   - flatpak

- import_tasks: 'caprine.yml'
  tags: 
    - caprine
    - communication
    - social
    - deb

- import_tasks: 'webtorrent.yml'
  tags:
    - webtorrent
    - deb

- import_tasks: 'authenticator.yml'

#- import_tasks: 'teamviewer.yml'
#  tags: teamviewer