
- name: Ramme | Get latest release from GitHub
  shell: get_latest_gh_release.sh "terkelg/ramme"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Ramme | Install package
  apt:
    deb: https://github.com/terkelg/ramme/releases/download/{{rc_version.stdout}}/Ramme_{{rc_version.stdout[1:]}}_amd64.deb
  become: true