
- name: Tui | Get latest release from GitHub
  shell: get_latest_gh_release.sh "rhysd/Tui"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Tui | Download tarball
  unarchive:
    src: "https://github.com/rhysd/Tui/releases/download/{{rc_version.stdout}}/Tui-linux-x64-{{rc_version.stdout[1:]}}.zip"
    dest: "{{ downloads_dir }}"
    remote_src: true

- name: Tui | Remove any previous installs
  file:
    path: /opt/Tui
    state: absent
  become: true

- name: Tui | Moves Tui to /opt
  command: mv Tui-linux-x64 /opt/Tui
  args:
    chdir: "{{downloads_dir}}"
  become: true

- name: Tui | Set correct permissions
  file:
    path: /opt/Tui
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Tui | Create .desktop file
  copy: 
    src: Tui.desktop
    dest: "{{ansible_env.HOME}}/.local/share/applications/Tui.desktop"
    force: no