- name: Adding current user to group sudo
  user: name='{{ user }}'
        groups=sudo
        append=yes

- name: Allow user to became root without entering password
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%sudo ALL='
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    validate: '/usr/sbin/visudo -cf %s'
  become: true