- name: Vim | Install
  apt:
    name: vim
    state: present
  become: true

- name: Vim | Create .vim/autoload directory
  file:
    path: ~/.vim/autoload
    state: directory

- name: Vim | Install vim plug
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim

- name: Vim | Install plugins
  shell: vim +PlugInstall +qall