- name: ctop | Get latest release from GitHub
  shell: get_latest_gh_release.sh "bcicen/ctop"
  register: version_result
  failed_when: rc_version.stdout == '' or rc_version.rc != 0
  
- name: ctop | Install package
  get_url: 
    url: https://github.com/bcicen/ctop/releases/download/{{version_result.stdout}}/ctop-{{version_result.stdout[1:]}}-linux-amd64 
    dest: /usr/local/bin/ctop
    mode: a+x
  become: true