- name: DevDocs | Get latest release from GitHub
  shell: get_latest_gh_release.sh "egoist/devdocs-desktop"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: DevDocs | Install package
  apt:
    deb: "https://github.com/egoist/devdocs-desktop/releases/download/{{rc_version.stdout}}/DevDocs_{{rc_version.stdout[1:]}}_amd64.deb"
  become: true