- name: DevRant | Get Latest version from GitHub Releases
  shell: get_latest_gh_release.sh "bcicen/ctop"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: DevRant | Install package
  apt:
    deb: "https://github.com/tahnik/devRantron/releases/download/{{rc_version.stdout}}/devrantron_{{rc.version.stdout[1:]}}_amd64.deb"
  become: true
