- name: Docker | Add APT key
  apt_key:
    url:  https://download.docker.com/linux/ubuntu/gpg 
    state: present
  become: true

- name: Docker | Add apt repository
  apt_repository:
    repo:  "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  become: true

- name: Docker | Install
  apt:
    name: docker.io
    state: present
  become: true

- name: Docker | Add current user to docker group
  user: 
    name: "{{ user }}"
    groups: docker
    append: yes
  become: true

- name: Docker | Refresh groups
  shell: newgrp docker

- name: Docker | Create daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    force: yes
  notify: 
    - restart docker
  become: true
  
- name: Docker | Install docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/1.18.0/docker-compose-Linux-{{ansible_architecture}}
    dest: "{{bin_dir}}/docker-compose"
    mode: a+x
  become: true

- name: Docker | Start Echoserver container
  docker_container:
    name: echoserver
    image: jamesw/http-echo-server
    state: started
    restart_policy: always
    expose:
    -  8081:8080
  become: true

- name: Docker | Start Dnsdock container
  docker_container:
    name: dnsdock
    image: aacebedo/dnsdock:latest-amd64
    state: started
    restart_policy: unless-stopped
    expose:
      - 172.17.0.1:53:53/udp
  become: true

- name: Docker | Create portainer data volume
  command: docker volume create portainer_data
  become: true

- name: Docker | Start Portainer container
  docker_container:
    name: portainer
    image: portainer/portainer
    state: started
    restart_policy: always
    expose:
      - 9000:9000
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data 
  become: true
