
- name: Helm | Get latest release from GitHub
  shell: get_latest_gh_release.sh "kubernetes/helm"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Helm | Download tarball
  unarchive:
    src: https://storage.googleapis.com/kubernetes-helm/helm-{{rc_version.stdout}}-linux-amd64.tar.gz
    remote_src: true
    dest: "{{downloads_dir}}"
    extra_opts: ['--strip-components=1']

- name: Helm | Install
  copy:
    src: "{{downloads_dir}}/helm"
    dest: /usr/local/bin/helm
    mode: a+x
  become: true