
- name: Hub | Get latest release from GitHub
  shell: get_latest_gh_release.sh "github/hub"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Hub | Download tarball
  unarchive: 
    src: https://github.com/github/hub/releases/download/{{rc_version.stdout}}/hub-linux-amd64-{{rc_version.stdout[1:]}}.tgz
    remote_src: true
    dest: "{{downloads_dir}}"

- name: Hub | Install
  shell: ./install
  args:
   chdir: "{{downloads_dir}}/hub-linux-amd64-{{rc_version.stdout[1:]}}"
  become: true