
- name: Kitematic | Get latest release from GitHub
  shell: get_latest_gh_release.sh "docker/kitematic"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Kitematic | Download tarball
  unarchive:
    src: https://github.com/docker/kitematic/releases/download/{{rc_version.stdout}}/Kitematic-{{rc_version.stdout[1:]}}-Ubuntu.zip
    remote_src: true
    dest: "{{downloads_dir}}"

- name: Kitematic | Install
  apt:
    deb:  "{{downloads_dir}}/dist/Kitematic_{{rc_version.stdout[1:]}}_amd64.deb"
