- name: Download kubectx tarball
  unarchive:
    src: https://github.com/ahmetb/kubectx/archive/master.tar.gz
    remote_src: true
    dest: "{{downloads_dir}}"
  become: true

- name: Copy files to bin directory
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    mode: a+x
  with_items:
    - { src: '{{downloads_dir}}/kubectx-master/kubectx', dest: '{{bin_dir}}/kubectx'}
    - { src: '{{downloads_dir}}/kubectx-master/kubens', dest: '{{bin_dir}}/kubens'}
  become: true

- name: Copy zsh completion
  copy:
    src: "{{item.src}}"
    dest: "{{item.dest}}"
    owner: "{{user}}"
    group: "{{group}}"
    force: no
  with_items:
    - { src: '{{downloads_dir}}/kubectx-master/completion/kubens.zsh', dest: '{{ansible_env.HOME}}/.zsh/completions/kubens.zsh'}
    - { src: '{{downloads_dir}}/kubectx-master/completion/kubectx.zsh', dest: '{{ansible_env.HOME}}/.zsh/completions/kubectx.zsh'}