- name: Helm | Get latest release from GitHub
  shell: get_latest_gh_release.sh "tstack/lnav"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Lnav | Download and install
  apt:
    deb: https://github.com/tstack/lnav/releases/download/v0.8.2/lnav_0.8.2_amd64.deb 
  become: true