- name: Installs MySQL Workbench dependencies
  apt: name={{item}} state=present
  with_items:
    - libpcrecpp0v5 
    - libzip4 
    - python-paramiko 
    - python-pyasn1
  become: true
  
- name: Install MySQL Workbench
  apt:
    deb: "https://dev.mysql.com/get/Downloads/MySQLGUITools/mysql-workbench-community-{{mysql_wb_version}}ubuntu17.10-amd64.deb"
  become: true