---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v0.7.0/install.sh | sh
   
- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts"

- name: Install NPM global packages
  npm:
    name: "{{item}}"
    global: yes
    state: latest
  with_items: "{{npm_global_packages}}"
  tags: npm

- name: Yarn - Add key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: true

- name: Yarn - Add repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn
  become: true

- name: Yarn - Install package
  apt:
    name: yarn
    state: latest
  become: true
