---

- name: node | Get latest nvm release from GitHub
  shell: get_latest_gh_release.sh "creationix/nvm"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: node | Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/{{rc_version.stdout}}/install.sh | sh
   
- name: node | Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install --lts && nvm use --lts"

- name: node | get latest version
  shell: /bin/bash -c "source ~/.nvm/nvm.sh && node -v"
  register: node_version
  
- name: node | Print version
  debug:
    msg: node_version.stdout

- name: node | Install NPM global packages
  npm:
    name: "{{item}}"
    global: yes
    state: latest
  with_items: "{{npm_global_packages}}"
  environment:
    PATH: "{{ansible_env.HOME}}/.nvm//versions/node/{{node_version.stdout}}/bin:{{ ansible_env.PATH }}"
  tags: npm
 
- name: Yarn | Add key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
  become: true

- name: Yarn | Add repository
  apt_repository:
    repo: deb https://dl.yarnpkg.com/debian/ stable main
    state: present
    filename: yarn
  become: true

- name: Yarn | Install package
  apt:
    name: yarn
    state: latest
  become: true
