- name: Openshift | Download package
  unarchive:
    src: https://github.com/openshift/origin/releases/download/v3.7.1/openshift-origin-client-tools-v3.7.1-ab0f056-linux-64bit.tar.gz
    remote_src: true
    extra_opts: ['--strip-components=1']
    dest: "{{setup_dir}}"
  
- name: Openshift | Install
  shell: mv oc {{bin_dir}}/oc
  args:
    chdir: "{{setup_dir}}"
  become: true