
- name: Openshift | Get latest release from GitHub
  shell: get_latest_gh_release.sh "kubernetes/helm"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Openshift | Download tarball
  unarchive:
    src: https://github.com/openshift/origin/releases/download/{{rc_version.stdout}}/openshift-origin-client-tools-{{rc_version.stdout}}-ab0f056-linux-64bit.tar.gz
    remote_src: true
    extra_opts: ['--strip-components=1']
    dest: "{{downloads_dir}}"
  
- name: Openshift | Install
  shell: mv oc {{bin_dir}}/oc
  args:
    chdir: "{{downloads_dir}}"
  become: true