- name: Pet | Get latest release from GitHub
  shell: get_latest_gh_release.sh "knqyf263/pet"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Pet | Download tarball
  unarchive: 
    src: https://github.com/knqyf263/pet/releases/download/{{rc_version.stdout}}/pet_{{rc_version.stdout[1:]}}_linux_amd64.zip
    remote_src: true
    dest: "{{downloads_dir}}"

- name: Pet | Make executable
  file:
    path: "{{downloads_dir}}/pet"
    mode: a+x
  become: true

- name: Pet | Move pet executable to correct location
  shell: mv pet /usr/local/bin
  args:
   chdir: "{{downloads_dir}}"
  become: true