#- name: PHP | Add ondrej PPA
#  apt_repository: 
#    repo: ppa:ondrej/php
#    state: present
#  become: true

- name: PHP | Install PHP packages
  apt:
    name: "{{item}}"
  with_items:
    - php7.2-common 
    - php7.2-cli 
    - php7.2-fpm 
    - php7.2-mysql 
    - php7.2-curl 
    - php7.2-xsl 
    - php7.2-intl 
    - php-xdebug 
    - php7.2-xml 
    - php7.2-mbstring 
    - php7.2-json 
    - php7.2-readline 
    - php-apcu
  become: true

- name: PHP | Install composer
  shell: "curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer"
  creates: "/usr/local/bin/composer"

- name: PHP | Ensure composer global directory exists
  file:
    path: "{{ ansible_env.HOME}}/.composer"
    state: directory
    mode: 0755

- name: PHP | Set default global composer.json
  copy: 
    src: "composer.json"
    dest: "{{ ansible_env.HOME}}/.composer/composer.json"
    force: no
  
- name: PHP | Install composer global packages
  composer:
    command: require
    global_command: true
    arguments: "{{item}}"
  with_items: "{{composer_global_packages}}"
