- name: PHP | Add ondrej PPA
  apt_repository: 
    repo: ppa:ondrej/php
    state: present
  become: true

- name: PHP | Install PHP packages
  apt:
    name: "{{item}}"
  with_items:
    - php7.1-common 
    - php7.1-cli 
    - php7.1-fpm 
    - php7.1-mysql 
    - php7.1-curl 
    - php7.1-xsl 
    - php7.1-intl 
    - php-xdebug 
    - php7.1-xml 
    - php7.1-sodium 
    - php7.1-mbstring 
    - php7.1-json 
    - php7.1-readline 
    - php-apcu
  become: true

- name: PHP | Install composer
  shell: "curl -sS https://getcomposer.org/installer | php && sudo mv composer.phar /usr/local/bin/composer"
  creates: "/usr/local/bin/composer"

- name: PHP | Ensure composer global directory exists
  file:
    path: "{{ ansible_env.HOME}}/.composer"
    state: directory
    mode: 0755

- name: PHP | Set default global composer.json
  copy: 
    src: "composer.json"
    dest: "{{ ansible_env.HOME}}/.composer/composer.json"
    force: no
  
- name: PHP | Install composer global packages
  composer:
    command: require
    global_command: true
    arguments: "{{item}}"
  with_items: "{{composer_global_packages}}"
