- name: Postman | Download and Extract Postman
  unarchive:
    src: https://dl.pstmn.io/download/latest/linux64 
    dest: /opt
    remote_src: yes
    owner: "{{user}}"
    group: "{{group}}"
  become: true

- name: Postman | Create Postman .desktop file
  copy:
    src: postman.desktop
    dest: "{{applications_dir}}/postman.desktop"

