- name: Python | Install
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python
    - python-pip
    - python-setuptools
  become: true

- name: Python | Install pip packages
  pip:
    name: "{{ item }}"
    state: latest
  with_items: "{{pip_global_packages}}"
  become: true