- name: Installs RVM GPG key
  gpg_import: 
     key_id: 409B6B1796C275462A1703113804BB82D39DC0E3
     state: present

- name: Download and install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby

- name: Get current ruby version
  shell: >
    /bin/zsh -c "source ~/.rvm/scripts/rvm && rvm current"
  register: ruby_version

- name: Install global Rubygems
  gem:
    name: "{{item}}"
    state: latest
  with_items: "{{rubygems}}"
  environment:
     PATH: "{{ansible_env.HOME}}/.rvm/rubies/{{ruby_version.stdout}}/bin/:{{ ansible_env.PATH }}"