- mame: Ruby | Install RVM dependencies
  apt:
    name: "{{item}}"
  with_items:
    - curl
    - gnupg 
    - build-essential

- name: Ruby | Installs RVM GPG key
  gpg_import: 
     key_id: 409B6B1796C275462A1703113804BB82D39DC0E3
     state: present

- name: Ruby | Download and install rvm
  shell: curl -sSL https://get.rvm.io | bash -s stable --ruby

- name: Ruby | Get current ruby version
  shell: >
    /bin/bash -c "source ~/.rvm/scripts/rvm && rvm current"
  register: ruby_version

- name: Ruby | Print version
  debug:
    msg: "{{ruby_version.stdout}}"

- name: Ruby | Install global Rubygems
  gem:
    name: "{{item}}"
    state: latest
  with_items: "{{rubygems}}"
  environment:
     PATH: "{{ansible_env.HOME}}/.rvm/rubies/{{ruby_version.stdout}}/bin/:{{ ansible_env.PATH }}"