
- name: Sterm | Get latest release from GitHub
  shell: get_latest_gh_release.sh "wercker/stern"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Sterm | Install
  get_url:
    url: https://github.com/wercker/stern/releases/download/{{rc_version.stdout[1:]}}/stern_linux_amd64
    dest: "{{bin_dir}}/sterm"
    mode: "a+x"
  become: true