
- name: Terraform | Get latest release from GitHub
  shell: get_latest_gh_release.sh "hashicorp/terraform"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: Terraform | Install
  unarchive:
    src: https://releases.hashicorp.com/terraform/{{rc_version.stdout[1:]}}/terraform_{{rc_version.stdout[1:]}}_linux_amd64.zip
    remote_src: true
    dest: "{{bin_dir}}"
    mode: u+rwx
  become: true