
- name: Vagrant | install
  apt:
    deb: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb"
  become: true

- name: Vagrant | Install plugins
  command: vagrant plugin install vagrant-hostsupdater vagrant-aws vagrant-digitalocean
