---
- name: add virtualbox oracle apt key
  become: yes
  apt_key: url="https://www.virtualbox.org/download/oracle_vbox.asc" state=present

- name: add virtualbox oracle apt key (2016)
  become: yes
  apt_key: url="https://www.virtualbox.org/download/oracle_vbox_2016.asc" state=present

- name: add virtualbox repository
  apt_repository:
    repo: deb https://download.virtualbox.org/virtualbox/debian {{ansible_distribution_release}} contrib
    state: present
  become: true

- name: install virtualbox
  become: yes
  apt:
    name: "{{item}}"
  with_items:
    - virtualbox
    - dkms
      
