
- name: VScode | Add apt key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true

- name: VScode | Add APT repository
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    filename: vscode.list
    state: present
  become: true

- name: VScode | Visual Studio code Install
  apt:
    name: code
    state: present
    update_cache: yes
  become: true

- name: VScode | Installs settings sync extension
  command: code --install-extension Shan.code-settings-sync