- name: FD | Get latest version from GitHub
  shell: get_latest_gh_release.sh "sharkdp/fd"
  register: rc_version
  failed_when: rc_version.stdout == '' or rc_version.rc != 0

- name: FD | Install latest version
  apt:
    deb: https://github.com/sharkdp/fd/releases/download/{{rc_version.stdout}}/fd_{{rc_version.stdout[1:]}}_amd64.deb
  become: true
  ignore_errors: True