- name: fzf | Clone repository
  git:
    repo: 'https://github.com/junegunn/fzf.git'
    dest: "{{ansible_env.HOME}}/.fzf"
    update: yes

- name: fzf | Run install command
  shell: ./install --all
  args:
    chdir: "{{ansible_env.HOME}}/.fzf"
